// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/mitchell/emart/eMart-business/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import UserOutlined from '/Users/mitchell/emart/eMart-business/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/UserOutlined';
import CrownOutlined from '/Users/mitchell/emart/eMart-business/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/Users/mitchell/emart/eMart-business/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, UserOutlined, CrownOutlined, TableOutlined };
